<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:annotation>
    <xs:appinfo>
      <dita:domainsModule xmlns:dita="http://dita.oasis-open.org/architecture/2005/">(topic bsExt-d)</dita:domainsModule>
    </xs:appinfo>
  </xs:annotation>

  <!-- GROUP DECLARATIONS -->
  <xs:group name="bsExt-d-bodydiv">
    <xs:choice>
      <xs:element ref="slider"/>
    </xs:choice>
  </xs:group>
  <xs:group name="bsExt-d-ph">
    <xs:choice>
      <xs:element ref="counter"/>
    </xs:choice>
  </xs:group>
  <xs:group name="bsExt-d-section">
    <xs:choice>
      <xs:element ref="parallax"/>
    </xs:choice>
  </xs:group>
  <xs:group name="bsExt-d-ol">
    <xs:choice>
      <xs:element ref="whitebox"/>
    </xs:choice>
  </xs:group>

  <!-- ELEMENT DECLARATIONS -->
  <!-- slider (bodydiv) -->
  <xs:element name="slider">
    <xs:complexType>
      <xs:complexContent>
        <xs:extension base="slider.class">
          <xs:attribute ref="class" default="+ topic/bodydiv bsExt-d/slider "/>
        </xs:extension>
      </xs:complexContent>
    </xs:complexType>
  </xs:element>
  <xs:complexType name="slider.class" mixed="true">
    <xs:sequence><xs:group ref="slider.content"/></xs:sequence>
    <xs:attributeGroup ref="slider.attributes"/>
  </xs:complexType>
  <xs:group name="slider.content">
    <xs:sequence>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:group ref="bodydiv.cnt"/>
        <xs:group ref="bodydiv"/>
        <xs:group ref="section"/>
      </xs:choice>
    </xs:sequence>
  </xs:group>
  <xs:attributeGroup name="slider.attributes">
    <xs:attributeGroup ref="univ-atts"/>
    <xs:attribute name="outputclass" type="xs:string" default="slider"/>
    <xs:attributeGroup ref="global-atts"/>
  </xs:attributeGroup>

  <!-- counter (ph) -->
  <xs:element name="counter">
    <xs:complexType>
      <xs:complexContent>
        <xs:extension base="counter.class">
          <xs:attribute ref="class" default="+ topic/ph bsExt-d/counter "/>
        </xs:extension>
      </xs:complexContent>
    </xs:complexType>
  </xs:element>
  <xs:complexType name="counter.class" mixed="true">
    <xs:sequence><xs:group ref="counter.content"/></xs:sequence>
    <xs:attributeGroup ref="counter.attributes"/>
  </xs:complexType>
  <xs:group name="counter.content">
    <xs:sequence>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:group ref="basic.ph"/>
      </xs:choice>
    </xs:sequence>
  </xs:group>
  <xs:attributeGroup name="counter.attributes">
    <xs:attribute name="keyref" type="xs:string"/>
    <xs:attributeGroup ref="univ-atts"/>
    <xs:attribute name="outputclass" type="xs:string" default="counter"/>
    <xs:attributeGroup ref="global-atts"/>
  </xs:attributeGroup>

  <!-- parallax (section) -->
  <xs:element name="parallax">
    <xs:complexType>
      <xs:complexContent>
        <xs:extension base="parallax.class">
          <xs:attribute ref="class" default="+ topic/section bsExt-d/parallax "/>
        </xs:extension>
      </xs:complexContent>
    </xs:complexType>
  </xs:element>
  <xs:complexType name="parallax.class" mixed="true">
    <xs:sequence><xs:group ref="parallax.content"/></xs:sequence>
    <xs:attributeGroup ref="parallax.attributes"/>
  </xs:complexType>
  <xs:group name="parallax.content">
    <xs:sequence>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:group ref="section.cnt"/>
      </xs:choice>
    </xs:sequence>
  </xs:group>
  <xs:attributeGroup name="parallax.attributes">
    <xs:attribute name="spectitle" type="xs:string"/>
    <xs:attributeGroup ref="univ-atts"/>
    <xs:attribute name="outputclass" type="xs:string" default="parallax"/>
    <xs:attributeGroup ref="global-atts"/>
  </xs:attributeGroup>

  <!-- whitebox (ol) -->
  <xs:element name="whitebox">
    <xs:complexType>
      <xs:complexContent>
        <xs:extension base="whitebox.class">
          <xs:attribute ref="class" default="+ topic/ol bsExt-d/whitebox "/>
        </xs:extension>
      </xs:complexContent>
    </xs:complexType>
  </xs:element>
  <xs:complexType name="whitebox.class">
    <xs:sequence><xs:group ref="whitebox.content"/></xs:sequence>
    <xs:attributeGroup ref="whitebox.attributes"/>
  </xs:complexType>
  <xs:group name="whitebox.content">
    <xs:sequence>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:group ref="li"/>
      </xs:choice>
    </xs:sequence>
  </xs:group>
  <xs:attributeGroup name="whitebox.attributes">
    <xs:attribute name="compact">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:enumeration value="yes"/>
          <xs:enumeration value="no"/>
          <xs:enumeration value="-dita-use-conref-target"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="spectitle" type="xs:string"/>
    <xs:attributeGroup ref="univ-atts"/>
    <xs:attribute name="outputclass" type="xs:string" default="whitebox"/>
    <xs:attributeGroup ref="global-atts"/>
  </xs:attributeGroup>

</xs:schema>
